### ISSUE TITLE
GT5U Changes Megathread

### ISSUE THREAD

**Issue by Rongmario** [Rongmario/Rising-Kingdom-1.7.10#2]
1. Allow ingots/dust/gems -> Blocks through vanilla crafting table (3*3).
2. Allow blocks -> ingots/dust/gems through vanilla crafting table (1 returns either 4 or 9 depending on material).
3. Enable Forge Hammer (Already have).

**Comment by MFernflower** [comment]
Remove recipe changes it does to other mods
